/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as TableRouteImport } from './routes/table'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesTransitionMetalRouteImport } from './routes/categories/transition-metal'
import { Route as CategoriesPostTransitionMetalRouteImport } from './routes/categories/post-transition-metal'
import { Route as CategoriesNonmetalRouteImport } from './routes/categories/nonmetal'
import { Route as CategoriesNobleGasRouteImport } from './routes/categories/noble-gas'
import { Route as CategoriesMetalloidRouteImport } from './routes/categories/metalloid'
import { Route as CategoriesLanthanideRouteImport } from './routes/categories/lanthanide'
import { Route as CategoriesHalogenRouteImport } from './routes/categories/halogen'
import { Route as CategoriesAlkalineEarthMetalRouteImport } from './routes/categories/alkaline-earth-metal'
import { Route as CategoriesAlkaliMetalRouteImport } from './routes/categories/alkali-metal'
import { Route as CategoriesActinideRouteImport } from './routes/categories/actinide'

const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesTransitionMetalRoute =
  CategoriesTransitionMetalRouteImport.update({
    id: '/categories/transition-metal',
    path: '/categories/transition-metal',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesPostTransitionMetalRoute =
  CategoriesPostTransitionMetalRouteImport.update({
    id: '/categories/post-transition-metal',
    path: '/categories/post-transition-metal',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesNonmetalRoute = CategoriesNonmetalRouteImport.update({
  id: '/categories/nonmetal',
  path: '/categories/nonmetal',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNobleGasRoute = CategoriesNobleGasRouteImport.update({
  id: '/categories/noble-gas',
  path: '/categories/noble-gas',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesMetalloidRoute = CategoriesMetalloidRouteImport.update({
  id: '/categories/metalloid',
  path: '/categories/metalloid',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesLanthanideRoute = CategoriesLanthanideRouteImport.update({
  id: '/categories/lanthanide',
  path: '/categories/lanthanide',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesHalogenRoute = CategoriesHalogenRouteImport.update({
  id: '/categories/halogen',
  path: '/categories/halogen',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesAlkalineEarthMetalRoute =
  CategoriesAlkalineEarthMetalRouteImport.update({
    id: '/categories/alkaline-earth-metal',
    path: '/categories/alkaline-earth-metal',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesAlkaliMetalRoute = CategoriesAlkaliMetalRouteImport.update({
  id: '/categories/alkali-metal',
  path: '/categories/alkali-metal',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesActinideRoute = CategoriesActinideRouteImport.update({
  id: '/categories/actinide',
  path: '/categories/actinide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/table': typeof TableRoute
  '/testing': typeof TestingRoute
  '/categories/actinide': typeof CategoriesActinideRoute
  '/categories/alkali-metal': typeof CategoriesAlkaliMetalRoute
  '/categories/alkaline-earth-metal': typeof CategoriesAlkalineEarthMetalRoute
  '/categories/halogen': typeof CategoriesHalogenRoute
  '/categories/lanthanide': typeof CategoriesLanthanideRoute
  '/categories/metalloid': typeof CategoriesMetalloidRoute
  '/categories/noble-gas': typeof CategoriesNobleGasRoute
  '/categories/nonmetal': typeof CategoriesNonmetalRoute
  '/categories/post-transition-metal': typeof CategoriesPostTransitionMetalRoute
  '/categories/transition-metal': typeof CategoriesTransitionMetalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/table': typeof TableRoute
  '/testing': typeof TestingRoute
  '/categories/actinide': typeof CategoriesActinideRoute
  '/categories/alkali-metal': typeof CategoriesAlkaliMetalRoute
  '/categories/alkaline-earth-metal': typeof CategoriesAlkalineEarthMetalRoute
  '/categories/halogen': typeof CategoriesHalogenRoute
  '/categories/lanthanide': typeof CategoriesLanthanideRoute
  '/categories/metalloid': typeof CategoriesMetalloidRoute
  '/categories/noble-gas': typeof CategoriesNobleGasRoute
  '/categories/nonmetal': typeof CategoriesNonmetalRoute
  '/categories/post-transition-metal': typeof CategoriesPostTransitionMetalRoute
  '/categories/transition-metal': typeof CategoriesTransitionMetalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/table': typeof TableRoute
  '/testing': typeof TestingRoute
  '/categories/actinide': typeof CategoriesActinideRoute
  '/categories/alkali-metal': typeof CategoriesAlkaliMetalRoute
  '/categories/alkaline-earth-metal': typeof CategoriesAlkalineEarthMetalRoute
  '/categories/halogen': typeof CategoriesHalogenRoute
  '/categories/lanthanide': typeof CategoriesLanthanideRoute
  '/categories/metalloid': typeof CategoriesMetalloidRoute
  '/categories/noble-gas': typeof CategoriesNobleGasRoute
  '/categories/nonmetal': typeof CategoriesNonmetalRoute
  '/categories/post-transition-metal': typeof CategoriesPostTransitionMetalRoute
  '/categories/transition-metal': typeof CategoriesTransitionMetalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/table'
    | '/testing'
    | '/categories/actinide'
    | '/categories/alkali-metal'
    | '/categories/alkaline-earth-metal'
    | '/categories/halogen'
    | '/categories/lanthanide'
    | '/categories/metalloid'
    | '/categories/noble-gas'
    | '/categories/nonmetal'
    | '/categories/post-transition-metal'
    | '/categories/transition-metal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/table'
    | '/testing'
    | '/categories/actinide'
    | '/categories/alkali-metal'
    | '/categories/alkaline-earth-metal'
    | '/categories/halogen'
    | '/categories/lanthanide'
    | '/categories/metalloid'
    | '/categories/noble-gas'
    | '/categories/nonmetal'
    | '/categories/post-transition-metal'
    | '/categories/transition-metal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/table'
    | '/testing'
    | '/categories/actinide'
    | '/categories/alkali-metal'
    | '/categories/alkaline-earth-metal'
    | '/categories/halogen'
    | '/categories/lanthanide'
    | '/categories/metalloid'
    | '/categories/noble-gas'
    | '/categories/nonmetal'
    | '/categories/post-transition-metal'
    | '/categories/transition-metal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  TableRoute: typeof TableRoute
  TestingRoute: typeof TestingRoute
  CategoriesActinideRoute: typeof CategoriesActinideRoute
  CategoriesAlkaliMetalRoute: typeof CategoriesAlkaliMetalRoute
  CategoriesAlkalineEarthMetalRoute: typeof CategoriesAlkalineEarthMetalRoute
  CategoriesHalogenRoute: typeof CategoriesHalogenRoute
  CategoriesLanthanideRoute: typeof CategoriesLanthanideRoute
  CategoriesMetalloidRoute: typeof CategoriesMetalloidRoute
  CategoriesNobleGasRoute: typeof CategoriesNobleGasRoute
  CategoriesNonmetalRoute: typeof CategoriesNonmetalRoute
  CategoriesPostTransitionMetalRoute: typeof CategoriesPostTransitionMetalRoute
  CategoriesTransitionMetalRoute: typeof CategoriesTransitionMetalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/transition-metal': {
      id: '/categories/transition-metal'
      path: '/categories/transition-metal'
      fullPath: '/categories/transition-metal'
      preLoaderRoute: typeof CategoriesTransitionMetalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/post-transition-metal': {
      id: '/categories/post-transition-metal'
      path: '/categories/post-transition-metal'
      fullPath: '/categories/post-transition-metal'
      preLoaderRoute: typeof CategoriesPostTransitionMetalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/nonmetal': {
      id: '/categories/nonmetal'
      path: '/categories/nonmetal'
      fullPath: '/categories/nonmetal'
      preLoaderRoute: typeof CategoriesNonmetalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/noble-gas': {
      id: '/categories/noble-gas'
      path: '/categories/noble-gas'
      fullPath: '/categories/noble-gas'
      preLoaderRoute: typeof CategoriesNobleGasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/metalloid': {
      id: '/categories/metalloid'
      path: '/categories/metalloid'
      fullPath: '/categories/metalloid'
      preLoaderRoute: typeof CategoriesMetalloidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/lanthanide': {
      id: '/categories/lanthanide'
      path: '/categories/lanthanide'
      fullPath: '/categories/lanthanide'
      preLoaderRoute: typeof CategoriesLanthanideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/halogen': {
      id: '/categories/halogen'
      path: '/categories/halogen'
      fullPath: '/categories/halogen'
      preLoaderRoute: typeof CategoriesHalogenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/alkaline-earth-metal': {
      id: '/categories/alkaline-earth-metal'
      path: '/categories/alkaline-earth-metal'
      fullPath: '/categories/alkaline-earth-metal'
      preLoaderRoute: typeof CategoriesAlkalineEarthMetalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/alkali-metal': {
      id: '/categories/alkali-metal'
      path: '/categories/alkali-metal'
      fullPath: '/categories/alkali-metal'
      preLoaderRoute: typeof CategoriesAlkaliMetalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/actinide': {
      id: '/categories/actinide'
      path: '/categories/actinide'
      fullPath: '/categories/actinide'
      preLoaderRoute: typeof CategoriesActinideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TableRoute: TableRoute,
  TestingRoute: TestingRoute,
  CategoriesActinideRoute: CategoriesActinideRoute,
  CategoriesAlkaliMetalRoute: CategoriesAlkaliMetalRoute,
  CategoriesAlkalineEarthMetalRoute: CategoriesAlkalineEarthMetalRoute,
  CategoriesHalogenRoute: CategoriesHalogenRoute,
  CategoriesLanthanideRoute: CategoriesLanthanideRoute,
  CategoriesMetalloidRoute: CategoriesMetalloidRoute,
  CategoriesNobleGasRoute: CategoriesNobleGasRoute,
  CategoriesNonmetalRoute: CategoriesNonmetalRoute,
  CategoriesPostTransitionMetalRoute: CategoriesPostTransitionMetalRoute,
  CategoriesTransitionMetalRoute: CategoriesTransitionMetalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
